[project]
name = "fdzc-ical-generator"
version = "0.1.0"
description = "Fuzhou University Zhicheng College ICS Schedule Generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "httpx>=0.28.1",
    "lxml>=6.0.0",
    "numpy>=2.3.2",
]
